import { MigrationInterface, QueryRunner } from "typeorm";

export class Tables1770066700346 implements MigrationInterface {
    name = 'Tables1770066700346'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "code" character varying(50), "faculty_id" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_429427d9251d6a3e7e1f4089d6" ON "departments" ("faculty_id", "name") `);
        await queryRunner.query(`CREATE TABLE "faculties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "code" character varying(50), "university_id" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fd83e4a09c7182ccf7bdb3770b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8dcbf837d9abe68b4b26f03795" ON "faculties" ("university_id", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."universities_type_enum" AS ENUM('federal', 'state', 'private')`);
        await queryRunner.query(`CREATE TABLE "universities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "code" character varying(50) NOT NULL, "state" character varying(100), "city" character varying(100), "address" text, "website" character varying(255), "type" "public"."universities_type_enum" NOT NULL DEFAULT 'federal', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a3e80913c5f263361d680fd7b43" UNIQUE ("code"), CONSTRAINT "PK_8da52f2cee6b407559fdbabf59e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_25b08a78732a663bb35872eaa7" ON "universities" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'moderator', 'admin', 'super_admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_yearofstudy_enum" AS ENUM('1', '2', '3', '4', '5', '6', 'postgraduate')`);
        await queryRunner.query(`CREATE TYPE "public"."users_verificationtier_enum" AS ENUM('none', 'tier_0', 'tier_1', 'tier_2')`);
        await queryRunner.query(`CREATE TYPE "public"."users_tier1reviewstatus_enum" AS ENUM('not_submitted', 'pending_review', 'pending_school_email', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone" character varying(20) NOT NULL, "phoneVerified" boolean NOT NULL DEFAULT false, "phoneVerifiedAt" TIMESTAMP, "emailVerified" boolean NOT NULL DEFAULT false, "emailVerifiedAt" TIMESTAMP, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "email" character varying(255) NOT NULL, "passwordHash" character varying(255) NOT NULL, "fullName" character varying(255) NOT NULL, "profilePhotoUrl" character varying(500), "bio" text, "yearOfStudy" "public"."users_yearofstudy_enum", "university_id" uuid NOT NULL, "faculty_id" uuid NOT NULL, "department_id" uuid NOT NULL, "verificationTier" "public"."users_verificationtier_enum" NOT NULL DEFAULT 'none', "schoolEmail" character varying(255), "schoolEmailVerified" boolean NOT NULL DEFAULT false, "schoolEmailVerifiedAt" TIMESTAMP, "tier1ReviewStatus" "public"."users_tier1reviewstatus_enum" NOT NULL DEFAULT 'not_submitted', "tier1ApprovedAt" TIMESTAMP, "tier1ApprovedBy" character varying(255), "tier1RejectionCount" integer NOT NULL DEFAULT '0', "tier1RejectionReason" text, "tier2VerifiedAt" TIMESTAMP, "bvnVerified" boolean NOT NULL DEFAULT false, "ninVerified" boolean NOT NULL DEFAULT false, "kycAttemptCount" integer NOT NULL DEFAULT '0', "isBanned" boolean NOT NULL DEFAULT false, "banReason" text, "banExpiresAt" TIMESTAMP, "bannedAt" TIMESTAMP, "bannedBy" character varying(255), "deviceId" character varying(255), "sellerRating" numeric(3,2) NOT NULL DEFAULT '0', "sellerRatingCount" integer NOT NULL DEFAULT '0', "buyerRating" numeric(3,2) NOT NULL DEFAULT '0', "buyerRatingCount" integer NOT NULL DEFAULT '0', "completedTransactions" integer NOT NULL DEFAULT '0', "refreshTokenHash" character varying(255), "lastLoginAt" TIMESTAMP, "lastActiveAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_2bef1cc35d499b5c4b5d68fcf7" ON "users" ("university_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_87365f808be784a424a51a3d93" ON "users" ("verificationTier") `);
        await queryRunner.query(`CREATE INDEX "IDX_599a094953bbdd37a0ee7094fd" ON "users" ("tier1ReviewStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_836026b660a661f0dbdc467bf1" ON "users" ("isBanned") `);
        await queryRunner.query(`CREATE INDEX "IDX_838d3c4a6792bbb0dc90031c2c" ON "users" ("deviceId") `);
        await queryRunner.query(`CREATE TYPE "public"."reports_type_enum" AS ENUM('post', 'comment', 'listing', 'user', 'message', 'housing')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_reason_enum" AS ENUM('spam', 'harassment', 'hate_speech', 'violence', 'nudity', 'scam', 'fake_listing', 'impersonation', 'misinformation', 'illegal_content', 'underage', 'self_harm', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('pending', 'under_review', 'action_taken', 'dismissed')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_action_enum" AS ENUM('none', 'warning_issued', 'content_removed', 'user_banned_temp', 'user_banned_perm')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reporter_id" uuid NOT NULL, "type" "public"."reports_type_enum" NOT NULL, "target_id" character varying NOT NULL, "reported_user_id" uuid, "reason" "public"."reports_reason_enum" NOT NULL, "description" text, "evidence" jsonb, "status" "public"."reports_status_enum" NOT NULL DEFAULT 'pending', "action" "public"."reports_action_enum", "reviewed_by_id" uuid, "reviewNotes" text, "reviewedAt" TIMESTAMP, "priority" integer NOT NULL DEFAULT '0', "reportCount" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9459b9bf907a3807ef7143d2ea" ON "reports" ("reporter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8401422324e7fa80304ed708e0" ON "reports" ("target_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9197bd0a7e06bb92648d9efed" ON "reports" ("reported_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dab4d78b3be05c1ca4a626f57f" ON "reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_09ce490b6501b21a96c789652e" ON "reports" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_54c2eccb4782bf6417371e1548" ON "reports" ("type", "target_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_781a2c0adee4125f1f6906a14a" ON "reports" ("status", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."warnings_reason_enum" AS ENUM('spam', 'harassment', 'inappropriate_content', 'policy_violation', 'scam_attempt', 'other')`);
        await queryRunner.query(`CREATE TABLE "warnings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "issued_by_id" uuid NOT NULL, "reason" "public"."warnings_reason_enum" NOT NULL, "message" text NOT NULL, "report_id" uuid, "acknowledged" boolean NOT NULL DEFAULT false, "acknowledgedAt" TIMESTAMP, "expiresAt" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_90d86ac75b7dcd1e29e9755e78e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a14eba00a6aaf0dc04f76aff0" ON "warnings" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_13b341476f4b85f95ccfe44c86" ON "warnings" ("user_id", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."verification_documents_type_enum" AS ENUM('student_id_front', 'student_id_back', 'school_fees_receipt', 'tuition_receipt', 'admission_letter')`);
        await queryRunner.query(`CREATE TYPE "public"."verification_documents_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "verification_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."verification_documents_type_enum" NOT NULL, "documentUrl" character varying(500) NOT NULL, "status" "public"."verification_documents_status_enum" NOT NULL DEFAULT 'pending', "rejectionReason" text, "reviewedAt" TIMESTAMP, "reviewedBy" character varying(255), "metadata" jsonb, "submissionAttempt" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b4dc59d87f87ce5a1bb1d3fe0bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_abf9dfa022250f71ccea9de73a" ON "verification_documents" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a11b51bbfd6ebaf03f3685f82" ON "verification_documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d7f82fa3fed4c0757f66658af" ON "verification_documents" ("user_id", "type") `);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "balance" numeric(12,2) NOT NULL DEFAULT '0', "lockedBalance" numeric(12,2) NOT NULL DEFAULT '0', "isLocked" boolean NOT NULL DEFAULT false, "lockReason" text, "lockedAt" TIMESTAMP, "bankAccountNumber" character varying(20), "bankCode" character varying(20), "bankName" character varying(100), "bankAccountName" character varying(255), "paystackRecipientCode" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_92558c08091598f7a4439586cda" UNIQUE ("user_id"), CONSTRAINT "REL_92558c08091598f7a4439586cd" UNIQUE ("user_id"), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_92558c08091598f7a4439586cd" ON "wallets" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_type_enum" AS ENUM('deposit', 'withdrawal', 'escrow_hold', 'escrow_release', 'escrow_refund', 'fee')`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_status_enum" AS ENUM('pending', 'completed', 'failed', 'reversed')`);
        await queryRunner.query(`CREATE TABLE "wallet_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "wallet_id" uuid NOT NULL, "type" "public"."wallet_transactions_type_enum" NOT NULL, "amount" numeric(12,2) NOT NULL, "status" "public"."wallet_transactions_status_enum" NOT NULL DEFAULT 'pending', "reference" character varying(100) NOT NULL, "description" text, "externalReference" character varying(255), "metadata" jsonb, "balanceBefore" numeric(12,2), "balanceAfter" numeric(12,2), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4b3d5cb7b4480ca1c3c367ebb45" UNIQUE ("reference"), CONSTRAINT "PK_5120f131bde2cda940ec1a621db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c57d19129968160f4db28fc8b2" ON "wallet_transactions" ("wallet_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b3d5cb7b4480ca1c3c367ebb4" ON "wallet_transactions" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_f297fd7508a3c4bff98fb9e1d6" ON "wallet_transactions" ("wallet_id", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."roommate_profiles_status_enum" AS ENUM('active', 'paused', 'matched')`);
        await queryRunner.query(`CREATE TYPE "public"."roommate_profiles_gender_enum" AS ENUM('male', 'female')`);
        await queryRunner.query(`CREATE TYPE "public"."roommate_profiles_cleanliness_enum" AS ENUM('very_clean', 'clean', 'moderate', 'relaxed')`);
        await queryRunner.query(`CREATE TYPE "public"."roommate_profiles_noiselevel_enum" AS ENUM('very_quiet', 'quiet', 'moderate', 'social')`);
        await queryRunner.query(`CREATE TYPE "public"."roommate_profiles_sleepschedule_enum" AS ENUM('early_bird', 'normal', 'night_owl', 'flexible')`);
        await queryRunner.query(`CREATE TYPE "public"."roommate_profiles_studyhabit_enum" AS ENUM('quiet_studier', 'background_noise', 'library_studier', 'flexible')`);
        await queryRunner.query(`CREATE TYPE "public"."roommate_profiles_preferredgender_enum" AS ENUM('male', 'female')`);
        await queryRunner.query(`CREATE TYPE "public"."roommate_profiles_preferredcleanliness_enum" AS ENUM('very_clean', 'clean', 'moderate', 'relaxed')`);
        await queryRunner.query(`CREATE TYPE "public"."roommate_profiles_preferrednoiselevel_enum" AS ENUM('very_quiet', 'quiet', 'moderate', 'social')`);
        await queryRunner.query(`CREATE TYPE "public"."roommate_profiles_preferredsleepschedule_enum" AS ENUM('early_bird', 'normal', 'night_owl', 'flexible')`);
        await queryRunner.query(`CREATE TABLE "roommate_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "university_id" uuid NOT NULL, "status" "public"."roommate_profiles_status_enum" NOT NULL DEFAULT 'active', "gender" "public"."roommate_profiles_gender_enum" NOT NULL, "age" integer NOT NULL, "bio" text, "budgetMin" numeric(12,2) NOT NULL, "budgetMax" numeric(12,2) NOT NULL, "preferredAreas" jsonb NOT NULL DEFAULT '[]', "moveInDate" date, "moveInFlexible" boolean NOT NULL DEFAULT false, "cleanliness" "public"."roommate_profiles_cleanliness_enum" NOT NULL DEFAULT 'clean', "noiseLevel" "public"."roommate_profiles_noiselevel_enum" NOT NULL DEFAULT 'moderate', "sleepSchedule" "public"."roommate_profiles_sleepschedule_enum" NOT NULL DEFAULT 'normal', "studyHabit" "public"."roommate_profiles_studyhabit_enum" NOT NULL DEFAULT 'flexible', "smokes" boolean NOT NULL DEFAULT false, "drinks" boolean NOT NULL DEFAULT false, "hasPets" boolean NOT NULL DEFAULT false, "allowsVisitors" boolean NOT NULL DEFAULT false, "preferredGender" "public"."roommate_profiles_preferredgender_enum", "preferredAgeMin" integer, "preferredAgeMax" integer, "preferredCleanliness" "public"."roommate_profiles_preferredcleanliness_enum", "preferredNoiseLevel" "public"."roommate_profiles_preferrednoiselevel_enum", "preferredSleepSchedule" "public"."roommate_profiles_preferredsleepschedule_enum", "nonSmokerOnly" boolean NOT NULL DEFAULT false, "nonDrinkerOnly" boolean NOT NULL DEFAULT false, "noPetsAllowed" boolean NOT NULL DEFAULT false, "interests" jsonb, "languages" jsonb, "viewCount" integer NOT NULL DEFAULT '0', "interestReceivedCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_864d8f9fd0b40e1ba708d78c86b" UNIQUE ("user_id"), CONSTRAINT "REL_864d8f9fd0b40e1ba708d78c86" UNIQUE ("user_id"), CONSTRAINT "PK_22d8653a53f54c379dffa6f813a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_864d8f9fd0b40e1ba708d78c86" ON "roommate_profiles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_518d918bdba862625d10c0774d" ON "roommate_profiles" ("university_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a8a400b6ea79eaebef25551fa" ON "roommate_profiles" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ea11303a19eb7f57a1c698e45" ON "roommate_profiles" ("budgetMin", "budgetMax") `);
        await queryRunner.query(`CREATE INDEX "IDX_9377f4bcd6fb0f278ef8cb2aa0" ON "roommate_profiles" ("gender", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8cff04392e91fbe358d0b316a" ON "roommate_profiles" ("university_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."roommate_interests_status_enum" AS ENUM('pending', 'accepted', 'declined')`);
        await queryRunner.query(`CREATE TABLE "roommate_interests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "from_user_id" uuid NOT NULL, "to_user_id" uuid NOT NULL, "status" "public"."roommate_interests_status_enum" NOT NULL DEFAULT 'pending', "message" text, "compatibilityScore" numeric(5,2), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5288d0f3f12e60fa748018cb45b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f9b54815cde5801ce1f5a75c3c" ON "roommate_interests" ("from_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc272f97e3c975d305d0f429d5" ON "roommate_interests" ("to_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa83b6111c2550c365fe0b0ff0" ON "roommate_interests" ("to_user_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_280b0aa2bc6cecd611447a4d1c" ON "roommate_interests" ("from_user_id", "to_user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."reviews_type_enum" AS ENUM('buyer_to_seller', 'seller_to_buyer')`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transaction_id" character varying NOT NULL, "reviewer_id" uuid NOT NULL, "reviewee_id" uuid NOT NULL, "type" "public"."reviews_type_enum" NOT NULL, "rating" smallint NOT NULL, "comment" text, "isEdited" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4a02104a7d9cc94ad2e871493e6" UNIQUE ("transaction_id", "reviewer_id", "type"), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6c41731907bca3d6513dbc642d" ON "reviews" ("transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_92e950a2513a79bb3fab273c92" ON "reviews" ("reviewer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7b3e1afadd6b52f3b6864745e" ON "reviews" ("reviewee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f357d362df2fd699f39e85d7e0" ON "reviews" ("reviewee_id", "type", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."posts_visibility_enum" AS ENUM('university', 'faculty', 'department')`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "author_id" character varying NOT NULL, "anonymous_id" character varying NOT NULL, "university_id" character varying NOT NULL, "faculty_id" uuid, "department_id" uuid, "visibility" "public"."posts_visibility_enum" NOT NULL DEFAULT 'university', "content" text NOT NULL, "image_urls" jsonb NOT NULL DEFAULT '[]', "poll" jsonb, "reactions" jsonb NOT NULL DEFAULT '[{"type":"like","count":0,"userIds":[]},{"type":"love","count":0,"userIds":[]},{"type":"laugh","count":0,"userIds":[]},{"type":"wow","count":0,"userIds":[]},{"type":"sad","count":0,"userIds":[]},{"type":"angry","count":0,"userIds":[]}]', "total_reactions" integer NOT NULL DEFAULT '0', "comment_count" integer NOT NULL DEFAULT '0', "view_count" integer NOT NULL DEFAULT '0', "is_edited" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "is_hidden" boolean NOT NULL DEFAULT false, "hidden_reason" text, "report_count" integer NOT NULL DEFAULT '0', "engagement_score" numeric(12,4) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_312c63be865c81b922e39c2475" ON "posts" ("author_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_926042354dd0cc746d042ab730" ON "posts" ("university_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2f4f5b3b63b38fec396b7078e4" ON "posts" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b2fdcb4fb94d189e0e679748a" ON "posts" ("author_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9874034d37e2110f9c85646cb" ON "posts" ("university_id", "engagement_score") `);
        await queryRunner.query(`CREATE INDEX "IDX_e31abbf251ed95100dc5bc396a" ON "posts" ("university_id", "visibility", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b932cf676feea1e77b00cdaa01" ON "posts" ("university_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "password_resets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "email" character varying(255) NOT NULL, "token" character varying(255) NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "usedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9b34edd5264effbbc875c266a9e" UNIQUE ("token"), CONSTRAINT "PK_4816377aa98211c1de34469e742" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f7a4c3bc48f24df007936d217b" ON "password_resets" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b34edd5264effbbc875c266a9" ON "password_resets" ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."listings_type_enum" AS ENUM('sell', 'buy_request')`);
        await queryRunner.query(`CREATE TYPE "public"."listings_category_enum" AS ENUM('electronics', 'furniture', 'books', 'clothing', 'appliances', 'phones', 'laptops', 'accessories', 'sports', 'beauty', 'food', 'services', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."listings_condition_enum" AS ENUM('new', 'like_new', 'used_good', 'used_fair')`);
        await queryRunner.query(`CREATE TYPE "public"."listings_visibilityscope_enum" AS ENUM('department', 'faculty', 'university')`);
        await queryRunner.query(`CREATE TYPE "public"."listings_deliveryoption_enum" AS ENUM('pickup_only', 'delivery_available', 'meetup')`);
        await queryRunner.query(`CREATE TYPE "public"."listings_status_enum" AS ENUM('active', 'sold', 'in_escrow', 'paused', 'deleted')`);
        await queryRunner.query(`CREATE TABLE "listings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seller_id" uuid NOT NULL, "university_id" uuid NOT NULL, "type" "public"."listings_type_enum" NOT NULL DEFAULT 'sell', "title" character varying(255) NOT NULL, "description" text NOT NULL, "category" "public"."listings_category_enum" NOT NULL, "condition" "public"."listings_condition_enum" NOT NULL, "price" numeric(12,2) NOT NULL, "isNegotiable" boolean NOT NULL DEFAULT true, "visibilityScope" "public"."listings_visibilityscope_enum" NOT NULL DEFAULT 'university', "faculty_id" uuid, "department_id" uuid, "deliveryOption" "public"."listings_deliveryoption_enum" NOT NULL DEFAULT 'meetup', "meetupLocation" text, "status" "public"."listings_status_enum" NOT NULL DEFAULT 'active', "viewCount" integer NOT NULL DEFAULT '0', "favoriteCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_520ecac6c99ec90bcf5a603cdcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6d2846ee6b337ce5225c8c7286" ON "listings" ("seller_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4dee06aa17d4eb85e2f2f56732" ON "listings" ("university_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6817abcea64908c38b6e6f7e72" ON "listings" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a65b771bc8228047f2f78a091" ON "listings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d29845ed8e40875af50bf4b713" ON "listings" ("seller_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3c3747e45502f561b66c1ee2a" ON "listings" ("university_id", "category", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec313a4188ce7267979c10bef0" ON "listings" ("university_id", "status", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "listing_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "listing_id" uuid NOT NULL, "url" character varying(500) NOT NULL, "position" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2abb5c9d795f27dbc4b10ced9dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_94041359df3c1b14c4420808d1" ON "listing_images" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_762301a6a63a8a43d42fa26d49" ON "listing_images" ("listing_id", "position") `);
        await queryRunner.query(`CREATE TYPE "public"."offers_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'countered', 'expired', 'withdrawn')`);
        await queryRunner.query(`CREATE TABLE "offers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "listing_id" uuid NOT NULL, "buyer_id" uuid NOT NULL, "seller_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "status" "public"."offers_status_enum" NOT NULL DEFAULT 'pending', "message" text, "counterAmount" numeric(12,2), "counterMessage" text, "respondedAt" TIMESTAMP, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4c88e956195bba85977da21b8f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff1371fdb408ba33d5d08a6162" ON "offers" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d62085256bc739c02d49a3c20" ON "offers" ("buyer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_434239966cb60e2dbc6178f993" ON "offers" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_11983781f9ceeb7392de6e38b0" ON "offers" ("buyer_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d23465c5503e88e9076bab9f43" ON "offers" ("listing_id", "status", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."moderation_queue_contenttype_enum" AS ENUM('post', 'comment', 'listing', 'message', 'profile', 'housing')`);
        await queryRunner.query(`CREATE TYPE "public"."moderation_queue_source_enum" AS ENUM('ai_flag', 'keyword_flag', 'user_report', 'manual')`);
        await queryRunner.query(`CREATE TYPE "public"."moderation_queue_category_enum" AS ENUM('spam', 'hate_speech', 'harassment', 'violence', 'adult_content', 'scam', 'misinformation', 'personal_info', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."moderation_queue_status_enum" AS ENUM('pending', 'in_review', 'approved', 'rejected', 'removed')`);
        await queryRunner.query(`CREATE TABLE "moderation_queue" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contentType" "public"."moderation_queue_contenttype_enum" NOT NULL, "content_id" character varying NOT NULL, "user_id" uuid NOT NULL, "source" "public"."moderation_queue_source_enum" NOT NULL, "category" "public"."moderation_queue_category_enum", "aiScore" numeric(5,4), "aiDetails" jsonb, "flaggedKeywords" jsonb, "contentSnapshot" text, "status" "public"."moderation_queue_status_enum" NOT NULL DEFAULT 'pending', "priority" integer NOT NULL DEFAULT '50', "reviewed_by_id" uuid, "reviewNotes" text, "reviewedAt" TIMESTAMP, "actionTaken" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aefa17b9c49a8db7a5b2ba0b369" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b259368f6442ae8e311cf6d9f" ON "moderation_queue" ("content_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f49756b8897a7b3c22f652a805" ON "moderation_queue" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1778cab8500554738987a257fc" ON "moderation_queue" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_cabed68486a35b43cb6b75ac3b" ON "moderation_queue" ("priority") `);
        await queryRunner.query(`CREATE INDEX "IDX_6b01d4bf3f7efc7a0925f2d897" ON "moderation_queue" ("contentType", "content_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_324f74dc5a9d60462b68c851b8" ON "moderation_queue" ("status", "priority", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('new_message', 'offer_received', 'offer_accepted', 'offer_rejected', 'offer_countered', 'offer_expired', 'escrow_initiated', 'escrow_confirmed', 'escrow_released', 'escrow_cancelled', 'escrow_disputed', 'review_received', 'listing_favorited', 'listing_sold', 'post_reaction', 'post_comment', 'comment_reply', 'roommate_interest', 'roommate_match', 'verification_approved', 'verification_rejected', 'warning_issued', 'account_banned', 'announcement')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "body" text NOT NULL, "data" jsonb, "imageUrl" character varying(500), "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "pushSent" boolean NOT NULL DEFAULT false, "pushSentAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ba28344602d583583b9ea1a50" ON "notifications" ("isRead") `);
        await queryRunner.query(`CREATE INDEX "IDX_f8119e95a07eeea356486ed134" ON "notifications" ("user_id", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c24be561656e7219e2566f6774" ON "notifications" ("user_id", "isRead", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."kyc_verifications_type_enum" AS ENUM('bvn', 'nin')`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_verifications_status_enum" AS ENUM('pending', 'success', 'failed')`);
        await queryRunner.query(`CREATE TABLE "kyc_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."kyc_verifications_type_enum" NOT NULL, "status" "public"."kyc_verifications_status_enum" NOT NULL DEFAULT 'pending', "youverifyReference" character varying(255), "attemptNumber" integer NOT NULL DEFAULT '1', "failureReason" text, "verifiedAt" TIMESTAMP, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_57b7c6b141dd225ce5dc95d7fb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1e23c7821d740b4881f773c39a" ON "kyc_verifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_78b8d37ee09f8a5a28b6d10636" ON "kyc_verifications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_31223ab57dd2c1285a79c2902c" ON "kyc_verifications" ("user_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."housing_listings_type_enum" AS ENUM('apartment', 'room', 'shared_room', 'hostel', 'self_contain', 'flat')`);
        await queryRunner.query(`CREATE TYPE "public"."housing_listings_status_enum" AS ENUM('available', 'rented', 'reserved', 'paused', 'deleted')`);
        await queryRunner.query(`CREATE TYPE "public"."housing_listings_furnishing_enum" AS ENUM('furnished', 'semi_furnished', 'unfurnished')`);
        await queryRunner.query(`CREATE TYPE "public"."housing_listings_genderpreference_enum" AS ENUM('male_only', 'female_only', 'any')`);
        await queryRunner.query(`CREATE TABLE "housing_listings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "landlord_id" uuid NOT NULL, "university_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text NOT NULL, "type" "public"."housing_listings_type_enum" NOT NULL, "status" "public"."housing_listings_status_enum" NOT NULL DEFAULT 'available', "pricePerMonth" numeric(12,2) NOT NULL, "pricePerYear" numeric(12,2), "cautionFee" numeric(12,2), "agentFee" numeric(12,2), "address" character varying(500) NOT NULL, "area" character varying(255) NOT NULL, "latitude" numeric(10,7), "longitude" numeric(10,7), "bedrooms" integer NOT NULL DEFAULT '1', "bathrooms" integer NOT NULL DEFAULT '1', "furnishing" "public"."housing_listings_furnishing_enum" NOT NULL DEFAULT 'unfurnished', "genderPreference" "public"."housing_listings_genderpreference_enum" NOT NULL DEFAULT 'any', "hasWater" boolean NOT NULL DEFAULT false, "hasElectricity" boolean NOT NULL DEFAULT false, "hasInternet" boolean NOT NULL DEFAULT false, "hasParking" boolean NOT NULL DEFAULT false, "hasSecurityGuard" boolean NOT NULL DEFAULT false, "hasGenerator" boolean NOT NULL DEFAULT false, "hasPrepaidMeter" boolean NOT NULL DEFAULT false, "isGated" boolean NOT NULL DEFAULT false, "allowsPets" boolean NOT NULL DEFAULT false, "otherAmenities" jsonb, "imageUrls" jsonb NOT NULL DEFAULT '[]', "videoUrl" jsonb, "rules" text, "availableFrom" date, "viewCount" integer NOT NULL DEFAULT '0', "inquiryCount" integer NOT NULL DEFAULT '0', "isVerified" boolean NOT NULL DEFAULT false, "verifiedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3cde713ab74eccd09fa7c439d3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aa7cafc0e8f660f2669abdc03a" ON "housing_listings" ("landlord_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f5f4cdb66f7a9470d4d2790b8" ON "housing_listings" ("university_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2628c8c8e2925abe9bb8f2723" ON "housing_listings" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c81e5b8aa9cab8b360e0e062f" ON "housing_listings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c81a9fa1b16e8a94faa7ffa49f" ON "housing_listings" ("pricePerMonth", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e692a68ff79c7a9565136900f4" ON "housing_listings" ("landlord_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd5bee82c48856af657ea218d7" ON "housing_listings" ("university_id", "type", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_26f8044313a9f7d2063c4ed7f7" ON "housing_listings" ("university_id", "status", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "favorites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "listing_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0f8db9b83a100398d2611a8c9d0" UNIQUE ("user_id", "listing_id"), CONSTRAINT "PK_890818d27523748dd36a4d1bdc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_35a6b05ee3b624d0de01ee5059" ON "favorites" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_74e0699c35d78e39b229d64f34" ON "favorites" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0d13eb4f397f2e41f34d1d6b4" ON "favorites" ("user_id", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "pushEnabled" boolean NOT NULL DEFAULT true, "emailEnabled" boolean NOT NULL DEFAULT true, "messagesEnabled" boolean NOT NULL DEFAULT true, "offersEnabled" boolean NOT NULL DEFAULT true, "escrowEnabled" boolean NOT NULL DEFAULT true, "reviewsEnabled" boolean NOT NULL DEFAULT true, "socialEnabled" boolean NOT NULL DEFAULT true, "housingEnabled" boolean NOT NULL DEFAULT true, "announcementsEnabled" boolean NOT NULL DEFAULT true, "quietHoursEnabled" boolean NOT NULL DEFAULT false, "quietHoursStart" TIME, "quietHoursEnd" TIME, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_64c90edc7310c6be7c10c96f675" UNIQUE ("user_id"), CONSTRAINT "REL_64c90edc7310c6be7c10c96f67" UNIQUE ("user_id"), CONSTRAINT "PK_e94e2b543f2f218ee68e4f4fad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_64c90edc7310c6be7c10c96f67" ON "notification_preferences" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."fcm_tokens_platform_enum" AS ENUM('ios', 'android', 'web')`);
        await queryRunner.query(`CREATE TABLE "fcm_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token" character varying(500) NOT NULL, "platform" "public"."fcm_tokens_platform_enum" NOT NULL, "deviceId" character varying(255), "deviceName" character varying(100), "isActive" boolean NOT NULL DEFAULT true, "lastUsedAt" TIMESTAMP, "failureCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_639c0f1d38d97d778122d4f2998" UNIQUE ("token"), CONSTRAINT "PK_0802a779d616597e9330bb9a7cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9fd867cabc75028a5625ce7b24" ON "fcm_tokens" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_639c0f1d38d97d778122d4f299" ON "fcm_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_c5678152794bb6ada963377ab7" ON "fcm_tokens" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_3093d5ec2df919064f062c4ee2" ON "fcm_tokens" ("user_id", "isActive") `);
        await queryRunner.query(`CREATE TYPE "public"."escrow_transactions_status_enum" AS ENUM('pending', 'buyer_confirmed', 'seller_confirmed', 'completed', 'disputed', 'refunded', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TABLE "escrow_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "buyer_id" uuid NOT NULL, "seller_id" uuid NOT NULL, "listing_id" uuid NOT NULL, "offer_id" uuid, "amount" numeric(12,2) NOT NULL, "fee" numeric(12,2) NOT NULL, "totalAmount" numeric(12,2) NOT NULL, "status" "public"."escrow_transactions_status_enum" NOT NULL DEFAULT 'pending', "buyerConfirmedAt" TIMESTAMP, "sellerConfirmedAt" TIMESTAMP, "releasedAt" TIMESTAMP, "refundedAt" TIMESTAMP, "expiresAt" TIMESTAMP NOT NULL, "notes" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_529d3ac2fa1b343b7beb59bd945" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d87d346e2538d3f6468adc8810" ON "escrow_transactions" ("buyer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfd9e57bc930b41520be3b61ab" ON "escrow_transactions" ("seller_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_af409dc455ad23c30662d4cd7f" ON "escrow_transactions" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_db0489f89d3533b8d6ff2fa703" ON "escrow_transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_356654ef1c52ebccd44b1ec1b3" ON "escrow_transactions" ("seller_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_62b6f367d33b0e84e586e1c705" ON "escrow_transactions" ("buyer_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a85bc84511bc2df81ac54cd8ce" ON "escrow_transactions" ("status", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."email_verifications_type_enum" AS ENUM('personal', 'school')`);
        await queryRunner.query(`CREATE TABLE "email_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "email" character varying(255) NOT NULL, "type" "public"."email_verifications_type_enum" NOT NULL, "token" character varying(255) NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "verifiedAt" TIMESTAMP, "resendCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_595be4c36e66b21d3fd14c73a24" UNIQUE ("token"), CONSTRAINT "PK_c1ea2921e767f83cd44c0af203f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4f1838323ae1dff5aa0014891" ON "email_verifications" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_595be4c36e66b21d3fd14c73a2" ON "email_verifications" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_cf482da18b9258b3801511d44e" ON "email_verifications" ("user_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."disputes_reason_enum" AS ENUM('item_not_received', 'item_not_as_described', 'item_damaged', 'seller_unresponsive', 'buyer_unresponsive', 'payment_issue', 'fraud', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_status_enum" AS ENUM('open', 'under_review', 'resolved_buyer', 'resolved_seller', 'resolved_split', 'closed')`);
        await queryRunner.query(`CREATE TABLE "disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "escrow_id" uuid NOT NULL, "opened_by_id" uuid NOT NULL, "reason" "public"."disputes_reason_enum" NOT NULL, "description" text NOT NULL, "evidence" jsonb, "status" "public"."disputes_status_enum" NOT NULL DEFAULT 'open', "resolved_by_id" uuid, "resolution" text, "buyerRefundAmount" numeric(12,2), "sellerReleaseAmount" numeric(12,2), "resolvedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3c97580d01c1a4b0b345c42a107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c621776068b60ee72409b89a92" ON "disputes" ("escrow_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ea46f4f2225f38d127063c367" ON "disputes" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3e36a382eb0855b0d4e765416" ON "disputes" ("status", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."conversations_type_enum" AS ENUM('listing_inquiry', 'direct_message')`);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."conversations_type_enum" NOT NULL DEFAULT 'listing_inquiry', "listing_id" uuid, "buyer_id" uuid, "participant1_id" uuid NOT NULL, "participant2_id" uuid NOT NULL, "lastMessagePreview" text, "lastMessageAt" TIMESTAMP, "last_message_sender_id" uuid, "participant1UnreadCount" integer NOT NULL DEFAULT '0', "participant2UnreadCount" integer NOT NULL DEFAULT '0', "isDeletedByParticipant1" boolean NOT NULL DEFAULT false, "isDeletedByParticipant2" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_30c796505d5cc405aa85d81866a" UNIQUE ("listing_id", "buyer_id"), CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c14948d6807e84b810dd4bed94" ON "conversations" ("listing_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_593d945aa73d054e2ed7caf9dc" ON "conversations" ("participant2_id", "updatedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d9eee1d3d0c7c6ad8e82661cb" ON "conversations" ("participant1_id", "updatedAt") `);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "content" text NOT NULL, "attachments" jsonb, "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "isSystemMessage" boolean NOT NULL DEFAULT false, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3bc55a7c3f9ed54b520bb5cfe2" ON "messages" ("conversation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_22133395bd13b970ccd0c34ab2" ON "messages" ("sender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e3d26aeccdd40aee0a1ad5f29" ON "messages" ("conversation_id", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" uuid NOT NULL, "parent_id" uuid, "author_id" character varying NOT NULL, "anonymous_id" character varying NOT NULL, "content" text NOT NULL, "reactions" jsonb NOT NULL DEFAULT '[{"type":"like","count":0,"userIds":[]},{"type":"love","count":0,"userIds":[]},{"type":"laugh","count":0,"userIds":[]}]', "total_reactions" integer NOT NULL DEFAULT '0', "reply_count" integer NOT NULL DEFAULT '0', "depth" integer NOT NULL DEFAULT '0', "is_edited" boolean NOT NULL DEFAULT false, "is_deleted" boolean NOT NULL DEFAULT false, "is_hidden" boolean NOT NULL DEFAULT false, "hidden_reason" text, "report_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_259bf9825d9d198608d1b46b0b" ON "comments" ("post_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6f93329801a93536da4241e38" ON "comments" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6d38899c31997c45d128a8973" ON "comments" ("author_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d13ed91f67738c84692c0dc7b" ON "comments" ("is_deleted") `);
        await queryRunner.query(`CREATE INDEX "IDX_d66c646e7738b2abdb6d00ee1e" ON "comments" ("author_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_c58e01e7bdce174e1cd72d0e65" ON "comments" ("post_id", "parent_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_06a1038b5b8f236c9ddb068af5" ON "comments" ("post_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."ban_appeals_status_enum" AS ENUM('pending', 'under_review', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "ban_appeals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "reason" text NOT NULL, "evidence" jsonb, "status" "public"."ban_appeals_status_enum" NOT NULL DEFAULT 'pending', "reviewed_by_id" uuid, "reviewNotes" text, "reviewedAt" TIMESTAMP, "originalBanReason" text, "originalBanDate" TIMESTAMP, "originalBanExpiry" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_df641ca7b2679eadd1efe526fe0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dbc872ecf29a2a524ce6c8d785" ON "ban_appeals" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_585859436c8a2e685abab98023" ON "ban_appeals" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad20290628d207d13dc015c078" ON "ban_appeals" ("status", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."articles_category_enum" AS ENUM('news', 'tips', 'announcements', 'campus_life', 'safety', 'events', 'marketplace_tips', 'housing', 'general')`);
        await queryRunner.query(`CREATE TYPE "public"."articles_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`CREATE TABLE "articles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "slug" character varying(300) NOT NULL, "excerpt" text, "content" text NOT NULL, "coverImageUrl" character varying(500), "category" "public"."articles_category_enum" NOT NULL DEFAULT 'general', "tags" jsonb, "status" "public"."articles_status_enum" NOT NULL DEFAULT 'draft', "isFeatured" boolean NOT NULL DEFAULT false, "author_id" uuid NOT NULL, "viewCount" integer NOT NULL DEFAULT '0', "bookmarkCount" integer NOT NULL DEFAULT '0', "publishedAt" TIMESTAMP, "metaDescription" character varying(160), "metaKeywords" jsonb, "readingTime" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1123ff6815c5b8fec0ba9fec370" UNIQUE ("slug"), CONSTRAINT "PK_0a6e2c450d83e0b6052c2793334" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1123ff6815c5b8fec0ba9fec37" ON "articles" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce46da62a5e412ebd1c0cf332e" ON "articles" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f0a73d2e1cc0db5557ae257d1" ON "articles" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7c3fddec96f02ac3cb007bb9d2" ON "articles" ("isFeatured") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ea038c4c5fe92c259f97356f7" ON "articles" ("publishedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_64ab4f1e38e0de40d877ac70be" ON "articles" ("category", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5ee5ab998b67e8a23cc36c9fe" ON "articles" ("status", "publishedAt") `);
        await queryRunner.query(`CREATE TABLE "article_bookmarks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "article_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_23c6941803cb958009a2ae01169" UNIQUE ("user_id", "article_id"), CONSTRAINT "PK_250b325640d4f923f9b7284ed10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8747c28c51535574eb6765460b" ON "article_bookmarks" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_72574ce48cd2a3deaaaad96e33" ON "article_bookmarks" ("article_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fbabdace10cd0458da028616eb" ON "article_bookmarks" ("user_id", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_db9cbab5eb895126fc1689dc2ad" FOREIGN KEY ("faculty_id") REFERENCES "faculties"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faculties" ADD CONSTRAINT "FK_e7e42880536e292f61869f816cb" FOREIGN KEY ("university_id") REFERENCES "universities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_2bef1cc35d499b5c4b5d68fcf7d" FOREIGN KEY ("university_id") REFERENCES "universities"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a0842240f363f156f8ee9377fad" FOREIGN KEY ("faculty_id") REFERENCES "faculties"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_0921d1972cf861d568f5271cd85" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_9459b9bf907a3807ef7143d2ead" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_a9197bd0a7e06bb92648d9efed2" FOREIGN KEY ("reported_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_0a8a98bba00898a2abb74147d52" FOREIGN KEY ("reviewed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warnings" ADD CONSTRAINT "FK_7a14eba00a6aaf0dc04f76aff02" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warnings" ADD CONSTRAINT "FK_afa6e864a63f3574831ff84d9fc" FOREIGN KEY ("issued_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warnings" ADD CONSTRAINT "FK_35ade38d6b1fa7c4424f0491f07" FOREIGN KEY ("report_id") REFERENCES "reports"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "verification_documents" ADD CONSTRAINT "FK_abf9dfa022250f71ccea9de73ae" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_c57d19129968160f4db28fc8b28" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roommate_profiles" ADD CONSTRAINT "FK_864d8f9fd0b40e1ba708d78c86b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roommate_profiles" ADD CONSTRAINT "FK_518d918bdba862625d10c0774d6" FOREIGN KEY ("university_id") REFERENCES "universities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roommate_interests" ADD CONSTRAINT "FK_f9b54815cde5801ce1f5a75c3c6" FOREIGN KEY ("from_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roommate_interests" ADD CONSTRAINT "FK_cc272f97e3c975d305d0f429d5c" FOREIGN KEY ("to_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_92e950a2513a79bb3fab273c92e" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_a7b3e1afadd6b52f3b6864745e3" FOREIGN KEY ("reviewee_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_resets" ADD CONSTRAINT "FK_f7a4c3bc48f24df007936d217be" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listings" ADD CONSTRAINT "FK_6d2846ee6b337ce5225c8c7286b" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listings" ADD CONSTRAINT "FK_4dee06aa17d4eb85e2f2f56732a" FOREIGN KEY ("university_id") REFERENCES "universities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listings" ADD CONSTRAINT "FK_43a6dd5bf51bf13bb4b77d78e74" FOREIGN KEY ("faculty_id") REFERENCES "faculties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listings" ADD CONSTRAINT "FK_47a95c543b4fab65fa081b8fc42" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "listing_images" ADD CONSTRAINT "FK_94041359df3c1b14c4420808d16" FOREIGN KEY ("listing_id") REFERENCES "listings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offers" ADD CONSTRAINT "FK_ff1371fdb408ba33d5d08a61629" FOREIGN KEY ("listing_id") REFERENCES "listings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offers" ADD CONSTRAINT "FK_8d62085256bc739c02d49a3c20e" FOREIGN KEY ("buyer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offers" ADD CONSTRAINT "FK_7fc60d9f105c297d03d857ffb0a" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderation_queue" ADD CONSTRAINT "FK_f49756b8897a7b3c22f652a8052" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderation_queue" ADD CONSTRAINT "FK_8f310c8d15ce19c51d22057ecfa" FOREIGN KEY ("reviewed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc_verifications" ADD CONSTRAINT "FK_1e23c7821d740b4881f773c39aa" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "housing_listings" ADD CONSTRAINT "FK_aa7cafc0e8f660f2669abdc03a0" FOREIGN KEY ("landlord_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "housing_listings" ADD CONSTRAINT "FK_1f5f4cdb66f7a9470d4d2790b88" FOREIGN KEY ("university_id") REFERENCES "universities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_74e0699c35d78e39b229d64f34f" FOREIGN KEY ("listing_id") REFERENCES "listings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_64c90edc7310c6be7c10c96f675" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fcm_tokens" ADD CONSTRAINT "FK_9fd867cabc75028a5625ce7b24c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD CONSTRAINT "FK_d87d346e2538d3f6468adc88108" FOREIGN KEY ("buyer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD CONSTRAINT "FK_cfd9e57bc930b41520be3b61abd" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD CONSTRAINT "FK_af409dc455ad23c30662d4cd7f8" FOREIGN KEY ("listing_id") REFERENCES "listings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" ADD CONSTRAINT "FK_89d8466a93ef9dfc7ffb978e848" FOREIGN KEY ("offer_id") REFERENCES "offers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verifications" ADD CONSTRAINT "FK_c4f1838323ae1dff5aa00148915" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_c621776068b60ee72409b89a92b" FOREIGN KEY ("escrow_id") REFERENCES "escrow_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_fe0d2e90a128089ca7cf7cf5455" FOREIGN KEY ("opened_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disputes" ADD CONSTRAINT "FK_46a6bddc5b940e568033271437a" FOREIGN KEY ("resolved_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_c14948d6807e84b810dd4bed949" FOREIGN KEY ("listing_id") REFERENCES "listings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_e84a792e292932b23435e5e1c44" FOREIGN KEY ("participant1_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_96c97706262674bc88318b681de" FOREIGN KEY ("participant2_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_d6f93329801a93536da4241e386" FOREIGN KEY ("parent_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ban_appeals" ADD CONSTRAINT "FK_dbc872ecf29a2a524ce6c8d7857" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ban_appeals" ADD CONSTRAINT "FK_50afe4b01d926c8bb21e06b8a7b" FOREIGN KEY ("reviewed_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_6515da4dff8db423ce4eb841490" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_bookmarks" ADD CONSTRAINT "FK_8747c28c51535574eb6765460bd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_bookmarks" ADD CONSTRAINT "FK_72574ce48cd2a3deaaaad96e334" FOREIGN KEY ("article_id") REFERENCES "articles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "article_bookmarks" DROP CONSTRAINT "FK_72574ce48cd2a3deaaaad96e334"`);
        await queryRunner.query(`ALTER TABLE "article_bookmarks" DROP CONSTRAINT "FK_8747c28c51535574eb6765460bd"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_6515da4dff8db423ce4eb841490"`);
        await queryRunner.query(`ALTER TABLE "ban_appeals" DROP CONSTRAINT "FK_50afe4b01d926c8bb21e06b8a7b"`);
        await queryRunner.query(`ALTER TABLE "ban_appeals" DROP CONSTRAINT "FK_dbc872ecf29a2a524ce6c8d7857"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_d6f93329801a93536da4241e386"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_96c97706262674bc88318b681de"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_e84a792e292932b23435e5e1c44"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_c14948d6807e84b810dd4bed949"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_46a6bddc5b940e568033271437a"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_fe0d2e90a128089ca7cf7cf5455"`);
        await queryRunner.query(`ALTER TABLE "disputes" DROP CONSTRAINT "FK_c621776068b60ee72409b89a92b"`);
        await queryRunner.query(`ALTER TABLE "email_verifications" DROP CONSTRAINT "FK_c4f1838323ae1dff5aa00148915"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP CONSTRAINT "FK_89d8466a93ef9dfc7ffb978e848"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP CONSTRAINT "FK_af409dc455ad23c30662d4cd7f8"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP CONSTRAINT "FK_cfd9e57bc930b41520be3b61abd"`);
        await queryRunner.query(`ALTER TABLE "escrow_transactions" DROP CONSTRAINT "FK_d87d346e2538d3f6468adc88108"`);
        await queryRunner.query(`ALTER TABLE "fcm_tokens" DROP CONSTRAINT "FK_9fd867cabc75028a5625ce7b24c"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_64c90edc7310c6be7c10c96f675"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_74e0699c35d78e39b229d64f34f"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593"`);
        await queryRunner.query(`ALTER TABLE "housing_listings" DROP CONSTRAINT "FK_1f5f4cdb66f7a9470d4d2790b88"`);
        await queryRunner.query(`ALTER TABLE "housing_listings" DROP CONSTRAINT "FK_aa7cafc0e8f660f2669abdc03a0"`);
        await queryRunner.query(`ALTER TABLE "kyc_verifications" DROP CONSTRAINT "FK_1e23c7821d740b4881f773c39aa"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "moderation_queue" DROP CONSTRAINT "FK_8f310c8d15ce19c51d22057ecfa"`);
        await queryRunner.query(`ALTER TABLE "moderation_queue" DROP CONSTRAINT "FK_f49756b8897a7b3c22f652a8052"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP CONSTRAINT "FK_7fc60d9f105c297d03d857ffb0a"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP CONSTRAINT "FK_8d62085256bc739c02d49a3c20e"`);
        await queryRunner.query(`ALTER TABLE "offers" DROP CONSTRAINT "FK_ff1371fdb408ba33d5d08a61629"`);
        await queryRunner.query(`ALTER TABLE "listing_images" DROP CONSTRAINT "FK_94041359df3c1b14c4420808d16"`);
        await queryRunner.query(`ALTER TABLE "listings" DROP CONSTRAINT "FK_47a95c543b4fab65fa081b8fc42"`);
        await queryRunner.query(`ALTER TABLE "listings" DROP CONSTRAINT "FK_43a6dd5bf51bf13bb4b77d78e74"`);
        await queryRunner.query(`ALTER TABLE "listings" DROP CONSTRAINT "FK_4dee06aa17d4eb85e2f2f56732a"`);
        await queryRunner.query(`ALTER TABLE "listings" DROP CONSTRAINT "FK_6d2846ee6b337ce5225c8c7286b"`);
        await queryRunner.query(`ALTER TABLE "password_resets" DROP CONSTRAINT "FK_f7a4c3bc48f24df007936d217be"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_a7b3e1afadd6b52f3b6864745e3"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_92e950a2513a79bb3fab273c92e"`);
        await queryRunner.query(`ALTER TABLE "roommate_interests" DROP CONSTRAINT "FK_cc272f97e3c975d305d0f429d5c"`);
        await queryRunner.query(`ALTER TABLE "roommate_interests" DROP CONSTRAINT "FK_f9b54815cde5801ce1f5a75c3c6"`);
        await queryRunner.query(`ALTER TABLE "roommate_profiles" DROP CONSTRAINT "FK_518d918bdba862625d10c0774d6"`);
        await queryRunner.query(`ALTER TABLE "roommate_profiles" DROP CONSTRAINT "FK_864d8f9fd0b40e1ba708d78c86b"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_c57d19129968160f4db28fc8b28"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "verification_documents" DROP CONSTRAINT "FK_abf9dfa022250f71ccea9de73ae"`);
        await queryRunner.query(`ALTER TABLE "warnings" DROP CONSTRAINT "FK_35ade38d6b1fa7c4424f0491f07"`);
        await queryRunner.query(`ALTER TABLE "warnings" DROP CONSTRAINT "FK_afa6e864a63f3574831ff84d9fc"`);
        await queryRunner.query(`ALTER TABLE "warnings" DROP CONSTRAINT "FK_7a14eba00a6aaf0dc04f76aff02"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_0a8a98bba00898a2abb74147d52"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_a9197bd0a7e06bb92648d9efed2"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_9459b9bf907a3807ef7143d2ead"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_0921d1972cf861d568f5271cd85"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a0842240f363f156f8ee9377fad"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_2bef1cc35d499b5c4b5d68fcf7d"`);
        await queryRunner.query(`ALTER TABLE "faculties" DROP CONSTRAINT "FK_e7e42880536e292f61869f816cb"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_db9cbab5eb895126fc1689dc2ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbabdace10cd0458da028616eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72574ce48cd2a3deaaaad96e33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8747c28c51535574eb6765460b"`);
        await queryRunner.query(`DROP TABLE "article_bookmarks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5ee5ab998b67e8a23cc36c9fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64ab4f1e38e0de40d877ac70be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ea038c4c5fe92c259f97356f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c3fddec96f02ac3cb007bb9d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f0a73d2e1cc0db5557ae257d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce46da62a5e412ebd1c0cf332e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1123ff6815c5b8fec0ba9fec37"`);
        await queryRunner.query(`DROP TABLE "articles"`);
        await queryRunner.query(`DROP TYPE "public"."articles_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."articles_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad20290628d207d13dc015c078"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_585859436c8a2e685abab98023"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbc872ecf29a2a524ce6c8d785"`);
        await queryRunner.query(`DROP TABLE "ban_appeals"`);
        await queryRunner.query(`DROP TYPE "public"."ban_appeals_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06a1038b5b8f236c9ddb068af5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c58e01e7bdce174e1cd72d0e65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d66c646e7738b2abdb6d00ee1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d13ed91f67738c84692c0dc7b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6d38899c31997c45d128a8973"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6f93329801a93536da4241e38"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_259bf9825d9d198608d1b46b0b"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e3d26aeccdd40aee0a1ad5f29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22133395bd13b970ccd0c34ab2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bc55a7c3f9ed54b520bb5cfe2"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d9eee1d3d0c7c6ad8e82661cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_593d945aa73d054e2ed7caf9dc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c14948d6807e84b810dd4bed94"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP TYPE "public"."conversations_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3e36a382eb0855b0d4e765416"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ea46f4f2225f38d127063c367"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c621776068b60ee72409b89a92"`);
        await queryRunner.query(`DROP TABLE "disputes"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_reason_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf482da18b9258b3801511d44e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_595be4c36e66b21d3fd14c73a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4f1838323ae1dff5aa0014891"`);
        await queryRunner.query(`DROP TABLE "email_verifications"`);
        await queryRunner.query(`DROP TYPE "public"."email_verifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a85bc84511bc2df81ac54cd8ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_62b6f367d33b0e84e586e1c705"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_356654ef1c52ebccd44b1ec1b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db0489f89d3533b8d6ff2fa703"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af409dc455ad23c30662d4cd7f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfd9e57bc930b41520be3b61ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d87d346e2538d3f6468adc8810"`);
        await queryRunner.query(`DROP TABLE "escrow_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."escrow_transactions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3093d5ec2df919064f062c4ee2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5678152794bb6ada963377ab7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_639c0f1d38d97d778122d4f299"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fd867cabc75028a5625ce7b24"`);
        await queryRunner.query(`DROP TABLE "fcm_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."fcm_tokens_platform_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64c90edc7310c6be7c10c96f67"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0d13eb4f397f2e41f34d1d6b4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74e0699c35d78e39b229d64f34"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35a6b05ee3b624d0de01ee5059"`);
        await queryRunner.query(`DROP TABLE "favorites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26f8044313a9f7d2063c4ed7f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd5bee82c48856af657ea218d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e692a68ff79c7a9565136900f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c81a9fa1b16e8a94faa7ffa49f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c81e5b8aa9cab8b360e0e062f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2628c8c8e2925abe9bb8f2723"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f5f4cdb66f7a9470d4d2790b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa7cafc0e8f660f2669abdc03a"`);
        await queryRunner.query(`DROP TABLE "housing_listings"`);
        await queryRunner.query(`DROP TYPE "public"."housing_listings_genderpreference_enum"`);
        await queryRunner.query(`DROP TYPE "public"."housing_listings_furnishing_enum"`);
        await queryRunner.query(`DROP TYPE "public"."housing_listings_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."housing_listings_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31223ab57dd2c1285a79c2902c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78b8d37ee09f8a5a28b6d10636"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e23c7821d740b4881f773c39a"`);
        await queryRunner.query(`DROP TABLE "kyc_verifications"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_verifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_verifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c24be561656e7219e2566f6774"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8119e95a07eeea356486ed134"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ba28344602d583583b9ea1a50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_324f74dc5a9d60462b68c851b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b01d4bf3f7efc7a0925f2d897"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cabed68486a35b43cb6b75ac3b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1778cab8500554738987a257fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f49756b8897a7b3c22f652a805"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b259368f6442ae8e311cf6d9f"`);
        await queryRunner.query(`DROP TABLE "moderation_queue"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_queue_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_queue_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_queue_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_queue_contenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d23465c5503e88e9076bab9f43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11983781f9ceeb7392de6e38b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_434239966cb60e2dbc6178f993"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d62085256bc739c02d49a3c20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff1371fdb408ba33d5d08a6162"`);
        await queryRunner.query(`DROP TABLE "offers"`);
        await queryRunner.query(`DROP TYPE "public"."offers_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_762301a6a63a8a43d42fa26d49"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94041359df3c1b14c4420808d1"`);
        await queryRunner.query(`DROP TABLE "listing_images"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec313a4188ce7267979c10bef0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3c3747e45502f561b66c1ee2a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d29845ed8e40875af50bf4b713"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a65b771bc8228047f2f78a091"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6817abcea64908c38b6e6f7e72"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4dee06aa17d4eb85e2f2f56732"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d2846ee6b337ce5225c8c7286"`);
        await queryRunner.query(`DROP TABLE "listings"`);
        await queryRunner.query(`DROP TYPE "public"."listings_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."listings_deliveryoption_enum"`);
        await queryRunner.query(`DROP TYPE "public"."listings_visibilityscope_enum"`);
        await queryRunner.query(`DROP TYPE "public"."listings_condition_enum"`);
        await queryRunner.query(`DROP TYPE "public"."listings_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."listings_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b34edd5264effbbc875c266a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7a4c3bc48f24df007936d217b"`);
        await queryRunner.query(`DROP TABLE "password_resets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b932cf676feea1e77b00cdaa01"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e31abbf251ed95100dc5bc396a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9874034d37e2110f9c85646cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b2fdcb4fb94d189e0e679748a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f4f5b3b63b38fec396b7078e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_926042354dd0cc746d042ab730"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_312c63be865c81b922e39c2475"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TYPE "public"."posts_visibility_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f357d362df2fd699f39e85d7e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7b3e1afadd6b52f3b6864745e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92e950a2513a79bb3fab273c92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c41731907bca3d6513dbc642d"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TYPE "public"."reviews_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_280b0aa2bc6cecd611447a4d1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa83b6111c2550c365fe0b0ff0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc272f97e3c975d305d0f429d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9b54815cde5801ce1f5a75c3c"`);
        await queryRunner.query(`DROP TABLE "roommate_interests"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_interests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8cff04392e91fbe358d0b316a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9377f4bcd6fb0f278ef8cb2aa0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ea11303a19eb7f57a1c698e45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a8a400b6ea79eaebef25551fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_518d918bdba862625d10c0774d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_864d8f9fd0b40e1ba708d78c86"`);
        await queryRunner.query(`DROP TABLE "roommate_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_profiles_preferredsleepschedule_enum"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_profiles_preferrednoiselevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_profiles_preferredcleanliness_enum"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_profiles_preferredgender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_profiles_studyhabit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_profiles_sleepschedule_enum"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_profiles_noiselevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_profiles_cleanliness_enum"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_profiles_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."roommate_profiles_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f297fd7508a3c4bff98fb9e1d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b3d5cb7b4480ca1c3c367ebb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c57d19129968160f4db28fc8b2"`);
        await queryRunner.query(`DROP TABLE "wallet_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92558c08091598f7a4439586cd"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d7f82fa3fed4c0757f66658af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a11b51bbfd6ebaf03f3685f82"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abf9dfa022250f71ccea9de73a"`);
        await queryRunner.query(`DROP TABLE "verification_documents"`);
        await queryRunner.query(`DROP TYPE "public"."verification_documents_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."verification_documents_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13b341476f4b85f95ccfe44c86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a14eba00a6aaf0dc04f76aff0"`);
        await queryRunner.query(`DROP TABLE "warnings"`);
        await queryRunner.query(`DROP TYPE "public"."warnings_reason_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_781a2c0adee4125f1f6906a14a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54c2eccb4782bf6417371e1548"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09ce490b6501b21a96c789652e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dab4d78b3be05c1ca4a626f57f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9197bd0a7e06bb92648d9efed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8401422324e7fa80304ed708e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9459b9bf907a3807ef7143d2ea"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_838d3c4a6792bbb0dc90031c2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_836026b660a661f0dbdc467bf1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_599a094953bbdd37a0ee7094fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87365f808be784a424a51a3d93"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bef1cc35d499b5c4b5d68fcf7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_tier1reviewstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_verificationtier_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_yearofstudy_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_25b08a78732a663bb35872eaa7"`);
        await queryRunner.query(`DROP TABLE "universities"`);
        await queryRunner.query(`DROP TYPE "public"."universities_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8dcbf837d9abe68b4b26f03795"`);
        await queryRunner.query(`DROP TABLE "faculties"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_429427d9251d6a3e7e1f4089d6"`);
        await queryRunner.query(`DROP TABLE "departments"`);
    }

}
